# Generated by Django 4.2.5 on 2023-10-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField()),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures_journal/', verbose_name='Изображение(превью)')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('published_is', models.BooleanField(default=False, verbose_name='признак публикации')),
                ('count_view', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'журнал',
                'verbose_name_plural': 'журналы',
            },
        ),
    ]
