# Generated by Django 4.2.5 on 2023-10-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
    ]
