# Generated by Django 4.2.5 on 2023-09-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_end_change',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_of_creation',
            field=models.DateTimeField(default='2018-11-20T15:58:44.767594-06:00', verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_comment='поле для названия продукта', max_length=250, verbose_name='Наименование'),
        ),
    ]
