# Generated by Django 4.2.5 on 2023-09-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_data_end_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_comment='поле для названия продукта', max_length=250, unique=True, verbose_name='Наименование'),
        ),
    ]
