# Generated by Django 4.2.5 on 2023-10-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_is',
            field=models.BooleanField(verbose_name='Активность'),
        ),
    ]
