# Generated by Django 4.2.5 on 2023-10-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_version_version_only_one_active_version_for_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='version',
            name='only_one_active_version_for_product',
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(condition=models.Q(('version_is_active', True)), fields=('product_name',), name='only_one_active_version_for_product', violation_error_message='Выберите одну активную версию'),
        ),
    ]
