# Generated by Django 4.2.5 on 2023-10-26 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_product_price_gte_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='создатель продукта'),
        ),
    ]
